de = {
    1: "Home",
    2: "Admin",
    3: "Login",
    4: "Logout",
    5: "Räume",
    6: "Geräte",
    7: "Admin Panel",
    8: "Benutzername",
    9: "Passwort",
    10: "E.D.I.T.H.",
    11: "Samples",
    12: "Benutzer",
    13: "Raum hinzufügen",
    14: "Raumname",
    15: "Hinzufügen",
    16: "Benutzer hinzufügen",
    17: "Smart Home",
    18: "Allgemein",
    19: "Persönlich",
    20: "Einstellungen",
    21: "Erscheinungsbild",
    22: "Farbschema",
    23: "Sprache",
    24: "Speichern",
    25: "2021 - Assistant",
    26: "Gerät hinzufügen",
    27: "Status",
    28: "Helligkeit",
    29: "Favoriten",
    30: "Alle Räume",
    31: "IP-Adresse",
    32: "ID",
    33: "Gerätename",
    34: "Gerätetyp (ID)",
    35: "Sprachsteuerung",
    36: "Der Key kann kostenfrei hier erstellt werden",
    37: "Favoriten festlegen",
    38: "Favoriten",
    39: "Position",
    40: "Mein Account",
    41: "Standard",
    42: "Deutsch",
    43: "Englisch",
    44: "Startbildschirm",
}
en = {
    1: "Home",
    2: "Admin",
    3: "Login",
    4: "Logout",
    5: "Rooms",
    6: "Devices",
    7: "Admin Panel",
    8: "Username",
    9: "Password",
    10: "Assistant",
    11: "Samples",
    12: "User",
    13: "Add Room",
    14: "Roomname",
    15: "Add",
    16: "Add User",
    17: "Smart Home",
    18: "General",
    19: "Personal",
    20: "Settings",
    21: "Appearance",
    22: "Colorscheme",
    23: "Language",
    24: "Save",
    25: "2021 - Assistant",
    26: "Add Device",
    27: "Status",
    28: "Brightness",
    29: "Favorites",
    30: "All Rooms",
    31: "IP-Address",
    32: "ID",
    33: "Devicename",
    34: "Devicetype (ID)",
    35: "Voice Assistant",
    36: "This is available for free here.",
    37: "Set favorites",
    38: "Favorites",
    39: "Position",
    40: "My Account",
    41: "Default",
    42: "German",
    43: "English",
    44: "Homescreen",
}